# Generated by Django 5.0.9 on 2024-09-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visits", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldTypes",
            fields=[
                (
                    "name",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pagevisit",
            name="time_stamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
